<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Vérifier si un élève existe, si oui le retourner
     */

    public function studentExists ($id)
    {
        $eleve = $this->find($id);
        if ($eleve)
            return $eleve;
        else
            return false;
    }

    public function duplicateStudent ($nom, $prenom, $dateNaiss)
    {
        if ($this->findBy(['nom' => $nom, 'prenom' => $prenom, 'dateNaiss' => $dateNaiss, ]))
            return true;
        else
            return false;
    }
}
