<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Vérifier si un élève existe, si oui le retourner
     */
    public function studentExists (int $id)
    {
        $eleve = $this->find($id);
        if ($eleve)
            return $eleve;
        else
            return false;
    }

    /**
     * Vérifier si un élève est un doublon
     * @param string $nom
     * @param string $prenom
     * @param string $dateNaiss
     * @return bool
     */
    public function duplicateStudent (string $nom, string $prenom, string $dateNaiss): bool
    {
        if ($this->findBy(['nom' => $nom, 'prenom' => $prenom, 'dateNaiss' => $dateNaiss]))
            return true;
        else
            return false;
    }
}
