<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Vérifier si une note existe déjà
     * @param int $id
     * @return bool|object|null
     */
    public function markExists (int $id)
    {
        if ($note = $this->find($id))
            return $note;
        else
            return false;
    }

    /**
     * Vérifier si une note est en double
     * @param string $valeur
     * @param string $matiere
     * @return bool
     */
    public function duplicateMark (string $valeur, string $matiere)
    {
        if ($this->findBy(['valeur' => $valeur, 'matiere' => $matiere]))
            return true;
        else
            return false;
    }

    /**
     * Récupérer les notes de toute la classe
     */
    public function getAllMarks ()
    {
        if ($notes = $this->findAll())
            return $notes;
        else
            return false;
    }

    /**
     * Récupérer le nombre de notes
     */
    public function notesCount ()
    {
        $qb = $this ->createQueryBuilder('a');
        $qb ->select('count(a.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Calculer la moyenne de toutes les notes
     */
    public function getClassAvg ()
    {
        $qb = $this ->createQueryBuilder('a');
        $qb ->select('avg(a.valeur)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
